[versions]
activity = "1.8.2"
agp = "8.3.0"
compose-compiler = "1.5.9"
javapoet = "1.13.0"
kotlin = "1.9.22"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity" }
android-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinKapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
